### ISSUE TITLE
Bug: Image is not available in a file.

### ISSUE THREAD

**Issue by AliGates915** [Romina875/Portfolio#1]
This is bug, because image is not visible at the hero section page. which means that **Main Page**
![bug](https://github.com/Romina875/Portfolio/assets/128673394/8f0f6d52-3c90-4f67-9499-eecff59bb1a5)
Now I will add the image file.

**Comment by Romina875** [comment]
Plz contribute to my code.
I will merge it.

**Comment by Romina875** [comment]
**Now you can check issue#1 is resolved.**

![Screenshot (14)](https://github.com/Romina875/Portfolio/assets/129262527/ed1dd60a-cb06-4b89-9810-7d01b2318001)
