### ISSUE TITLE
feat: Hero Section Name At the new Line

### ISSUE THREAD

**Issue by Romina875** [Romina875/Portfolio#2]
![Capture](https://github.com/Romina875/Portfolio/assets/129262527/1e491a21-a023-4ae8-98da-7c25024c1e87)

You can see the Hero Section Name , I wana My ame **"Romina Mir"** at the new line.Now you can resolved my issue#2

**Comment by AliGates915** [comment]
Ok I will Try it.

**Comment by Aneal07** [comment]
You can do it by adding <br> before your name. It will solve the problem.
